name       : wget
version    : 1.19.5
release    : 15
source     :
    - https://ftp.gnu.org/gnu/wget/wget-1.19.5.tar.lz : 29fbe6f3d5408430c572a63fe32bd43d5860f32691173dfd84edc06869edca75
homepage   : https://www.gnu.org/software/wget/
license    : GPL-3.0-or-later
component  : network.clients
summary    : retrieves files from the web
description: |
    GNU Wget is a free software package for retrieving files using HTTP, HTTPS and FTP, the most widely-used Internet protocols. It is a non-interactive commandline tool, so it may easily be called from scripts, cron jobs, terminals without X-Windows support, etc.
builddeps  :
    - pkgconfig(libpcre)
    - pkgconfig(libcrypto)
    - pkgconfig(zlib)
optimize   : size
setup      : |
    %patch -p1 < $pkgfiles/security/CVE-2017-6508.patch
    %configure --with-ssl=openssl
build      : |
    %make
install    : |
    %make_install
