name       : wget
version    : '1.21'
release    : 21
source     :
    - https://ftp.gnu.org/gnu/wget/wget-1.21.tar.gz : b3bc1a9bd0c19836c9709c318d41c19c11215a07514f49f89b40b9d50ab49325
homepage   : https://www.gnu.org/software/wget/
license    : GPL-3.0-or-later
component  : network.clients
summary    : retrieves files from the web
description: |
    GNU Wget is a free software package for retrieving files using HTTP, HTTPS and FTP, the most widely-used Internet protocols. It is a non-interactive commandline tool, so it may easily be called from scripts, cron jobs, terminals without X-Windows support, etc.
optimize   : size
builddeps  :
    - pkgconfig(libpcre)
setup      : |
    %patch -p1 < $pkgfiles/security/CVE-2017-6508.patch
    %configure --with-ssl=openssl
build      : |
    %make
install    : |
    %make_install
