name       : wget
version    : '1.19'
release    : 8
source     :
    - http://ftp.gnu.org/gnu/wget/wget-1.19.tar.xz : 0f1157bbf4daae19f3e1ddb70c6ccb2067feb834a6aa23c9d9daa7f048606384
homepage   : http://www.gnu.org/software/wget/
license    :
    - GPL-3.0
summary    : retrieves files from the web
component  : network.clients
builddeps  :
    - pkgconfig(libpcre)
    - pkgconfig(libcrypto)
    - pkgconfig(zlib)
optimize   : size
description: |
    GNU Wget is a free software package for retrieving files using HTTP, HTTPS and FTP, the most widely-used Internet protocols. It is a non-interactive commandline tool, so it may easily be called from scripts, cron jobs, terminals without X-Windows support, etc.
setup      : |
    %configure --with-ssl=openssl
build      : |
    %make
install    : |
    %make_install
