name        : wget
version     : 1.16.3
release     : 4
source      :
    - http://ftp.gnu.org/gnu/wget/wget-1.16.3.tar.xz : 67f7b7b0f5c14db633e3b18f53172786c001e153d545cfc85d82759c5c2ffb37
homepage    : http://www.gnu.org/software/wget/
license     :
    - GPL-3.0
summary     : retrieves files from the web
component   : network.clients
builddeps   :
    - pkgconfig(libpcre)
    - pkgconfig(libcrypto)
    - pkgconfig(zlib)
description : |
    GNU Wget is a free software package for retrieving files using HTTP, HTTPS and FTP, the most widely-used Internet protocols. It is a non-interactive commandline tool, so it may easily be called from scripts, cron jobs, terminals without X-Windows support, etc.
setup      : |
    %configure --with-ssl=openssl
build      : |
    %make
install    : |
    %make_install
